version: '3.8'
services:
  backend:
    build: ./Backend/node_server
    restart: always
    environment:
      - DB_HOST=postgres_db
      - DB_USER=app_legend
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=Hur
      - JWT_SECRET=${JWT_SECRET}
      - ML_SERVICE_URL=http://ml_server:8000
    volumes:
      - ./Backend/node_server/images/posts:/app/images/posts
      - ./Backend/node_server/images/profiles:/app/images/profiles
    networks:
      - app-network
    depends_on:
      - postgres_db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - backend

  postgres_db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=app_legend
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=Hur
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml_server:
    build: ./Backend/ml_server
    restart: always
    networks:
      - app-network
    volumes:
      - ml_model_cache:/root/.cache

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  ml_model_cache:
